version: '3'

services: 
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./db:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment: 
      PMA_HOST: db
    ports:
      - 8080:80