version: '2'

services: 
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment: 
      PMA_HOST: db
    ports:
      - 8080:80
  
  mongo:
    image: mongo
    restart: always
    ports:
    - "27017:27017"
    volumes:
    - ./mongodb:/data/db
